require 'simplecov'
SimpleCov.start do
  add_filter '/spec/'
end

require_relative '../lib/shift_care'

# This file was generated by the `rspec --init` command
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups
  config.filter_run_when_matching :focus
  config.example_status_persistence_file_path = "spec/examples.txt"
  config.disable_monkey_patching!
  config.warnings = true

  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  config.order = :random
  Kernel.srand config.seed
end

# Path to test fixtures
def fixtures_path
  File.join(File.dirname(__FILE__), 'fixtures')
end

# Path to test clients.json
def test_clients_path
  File.join(fixtures_path, 'clients.json')
end